### ISSUE TITLE
`num.zero_ttl` renamed to `num.expired` in unbound 1.10.1

### ISSUE THREAD

**Issue by bengentil** [svartalf/unbound-telemetry#10]
Following this commit
https://github.com/NLnetLabs/unbound/commit/f7fe95ad7bae690781f9b78ca252a44fc072ca33

The statistic `num.zero_ttl` has been renamed to `num.expired`, causing telemetry to ignore this "new" statistic:
```
WARN  [unbound_telemetry::statistics::parser] Unable to parse 'thread0.num.expired=0', unknown key
WARN  [unbound_telemetry::statistics::parser] Unable to parse 'thread1.num.expired=0', unknown key
WARN  [unbound_telemetry::statistics::parser] Unable to parse 'total.num.expired=0', unknown key
```

**Comment by svartalf** [comment]
Thanks for the heads up, @bengentil, fixed!
