### ISSUE TITLE
Unable to observe unbound statistics: Unable to parse 'CLASS0' value

### ISSUE THREAD

**Issue by mahdiadnan** [svartalf/unbound-telemetry#36]
Hi,

I'm getting the following error:
Unable to observe unbound statistics: Unable to parse 'CLASS0' value

Telemetry version: unbound-telemetry 0.1.0

Stats output:

thread0.num.queries=610401755
thread0.num.queries_ip_ratelimited=0
thread0.num.cachehits=588162357
thread0.num.cachemiss=22239398
thread0.num.prefetch=4495936
thread0.num.zero_ttl=0
thread0.num.recursivereplies=22239338
thread0.requestlist.avg=101.415
thread0.requestlist.max=1808
thread0.requestlist.overwritten=0
thread0.requestlist.exceeded=0
thread0.requestlist.current.all=124
thread0.requestlist.current.user=60
thread0.recursion.time.avg=0.311847
thread0.recursion.time.median=0.104955
thread0.tcpusage=3
thread1.num.queries=611224065
thread1.num.queries_ip_ratelimited=0
thread1.num.cachehits=588592233
thread1.num.cachemiss=22631832
thread1.num.prefetch=4496075
thread1.num.zero_ttl=0
thread1.num.recursivereplies=22631768
thread1.requestlist.avg=102.598
thread1.requestlist.max=1919
thread1.requestlist.overwritten=0
thread1.requestlist.exceeded=0
thread1.requestlist.current.all=106
thread1.requestlist.current.user=64
thread1.recursion.time.avg=0.312118
thread1.recursion.time.median=0.104841
thread1.tcpusage=0
thread2.num.queries=609543483
thread2.num.queries_ip_ratelimited=0
thread2.num.cachehits=587407795
thread2.num.cachemiss=22135688
thread2.num.prefetch=4491317
thread2.num.zero_ttl=0
thread2.num.recursivereplies=22135634
thread2.requestlist.avg=100.85
thread2.requestlist.max=2012
thread2.requestlist.overwritten=0
thread2.requestlist.exceeded=0
thread2.requestlist.current.all=110
thread2.requestlist.current.user=54
thread2.recursion.time.avg=0.316015
thread2.recursion.time.median=0.104826
thread2.tcpusage=0
thread3.num.queries=609563048
thread3.num.queries_ip_ratelimited=0
thread3.num.cachehits=587162114
thread3.num.cachemiss=22400934
thread3.num.prefetch=4497989
thread3.num.zero_ttl=0
thread3.num.recursivereplies=22400890
thread3.requestlist.avg=101.969
thread3.requestlist.max=1876
thread3.requestlist.overwritten=0
thread3.requestlist.exceeded=0
thread3.requestlist.current.all=97
thread3.requestlist.current.user=44
thread3.recursion.time.avg=0.315178
thread3.recursion.time.median=0.104789
thread3.tcpusage=4
thread4.num.queries=611964503
thread4.num.queries_ip_ratelimited=0
thread4.num.cachehits=588905687
thread4.num.cachemiss=23058816
thread4.num.prefetch=4502846
thread4.num.zero_ttl=0
thread4.num.recursivereplies=23058733
thread4.requestlist.avg=101.907
thread4.requestlist.max=2091
thread4.requestlist.overwritten=0
thread4.requestlist.exceeded=0
thread4.requestlist.current.all=143
thread4.requestlist.current.user=83
thread4.recursion.time.avg=0.304069
thread4.recursion.time.median=0.104932
thread4.tcpusage=2
thread5.num.queries=612029690
thread5.num.queries_ip_ratelimited=0
thread5.num.cachehits=589898464
thread5.num.cachemiss=22131226
thread5.num.prefetch=4497126
thread5.num.zero_ttl=0
thread5.num.recursivereplies=22131177
thread5.requestlist.avg=101.263
thread5.requestlist.max=1873
thread5.requestlist.overwritten=0
thread5.requestlist.exceeded=0
thread5.requestlist.current.all=96
thread5.requestlist.current.user=49
thread5.recursion.time.avg=0.314101
thread5.recursion.time.median=0.104745
thread5.tcpusage=1
thread6.num.queries=609613369
thread6.num.queries_ip_ratelimited=0
thread6.num.cachehits=586940742
thread6.num.cachemiss=22672627
thread6.num.prefetch=4497511
thread6.num.zero_ttl=0
thread6.num.recursivereplies=22672576
thread6.requestlist.avg=101.29
thread6.requestlist.max=1899
thread6.requestlist.overwritten=0
thread6.requestlist.exceeded=0
thread6.requestlist.current.all=93
thread6.requestlist.current.user=51
thread6.recursion.time.avg=0.306884
thread6.recursion.time.median=0.104772
thread6.tcpusage=0
thread7.num.queries=608759644
thread7.num.queries_ip_ratelimited=0
thread7.num.cachehits=586439335
thread7.num.cachemiss=22320309
thread7.num.prefetch=4490196
thread7.num.zero_ttl=0
thread7.num.recursivereplies=22320247
thread7.requestlist.avg=102.314
thread7.requestlist.max=1940
thread7.requestlist.overwritten=0
thread7.requestlist.exceeded=0
thread7.requestlist.current.all=109
thread7.requestlist.current.user=62
thread7.recursion.time.avg=0.316621
thread7.recursion.time.median=0.104756
thread7.tcpusage=3
total.num.queries=4883099557
total.num.queries_ip_ratelimited=0
total.num.cachehits=4703508727
total.num.cachemiss=179590830
total.num.prefetch=35968996
total.num.zero_ttl=0
total.num.recursivereplies=179590363
total.requestlist.avg=101.703
total.requestlist.max=2091
total.requestlist.overwritten=0
total.requestlist.exceeded=0
total.requestlist.current.all=878
total.requestlist.current.user=467
total.recursion.time.avg=0.312056
total.recursion.time.median=0.104827
total.tcpusage=13
time.now=1609591842.801112
time.up=181085.454982
time.elapsed=181085.454982
mem.cache.rrset=570420018
mem.cache.message=570425143
mem.mod.iterator=16588
mem.mod.validator=140747857
mem.mod.respip=0
mem.mod.subnet=140552
mem.mod.ipsecmod=0
mem.streamwait=0
histogram.000000.000000.to.000000.000001=13735612
histogram.000000.000001.to.000000.000002=0
histogram.000000.000002.to.000000.000004=0
histogram.000000.000004.to.000000.000008=0
histogram.000000.000008.to.000000.000016=0
histogram.000000.000016.to.000000.000032=1
histogram.000000.000032.to.000000.000064=97
histogram.000000.000064.to.000000.000128=377
histogram.000000.000128.to.000000.000256=698
histogram.000000.000256.to.000000.000512=1367
histogram.000000.000512.to.000000.001024=2558
histogram.000000.001024.to.000000.002048=5169
histogram.000000.002048.to.000000.004096=11247
histogram.000000.004096.to.000000.008192=2428458
histogram.000000.008192.to.000000.016384=2384985
histogram.000000.016384.to.000000.032768=408683
histogram.000000.032768.to.000000.065536=180786
histogram.000000.065536.to.000000.131072=117815982
histogram.000000.131072.to.000000.262144=21102257
histogram.000000.262144.to.000000.524288=15426745
histogram.000000.524288.to.000001.000000=2540766
histogram.000001.000000.to.000002.000000=1720689
histogram.000002.000000.to.000004.000000=1360061
histogram.000004.000000.to.000008.000000=139129
histogram.000008.000000.to.000016.000000=112267
histogram.000016.000000.to.000032.000000=120539
histogram.000032.000000.to.000064.000000=29664
histogram.000064.000000.to.000128.000000=22341
histogram.000128.000000.to.000256.000000=11351
histogram.000256.000000.to.000512.000000=12785
histogram.000512.000000.to.001024.000000=13622
histogram.001024.000000.to.002048.000000=2088
histogram.002048.000000.to.004096.000000=38
histogram.004096.000000.to.008192.000000=1
histogram.008192.000000.to.016384.000000=0
histogram.016384.000000.to.032768.000000=0
histogram.032768.000000.to.065536.000000=0
histogram.065536.000000.to.131072.000000=0
histogram.131072.000000.to.262144.000000=0
histogram.262144.000000.to.524288.000000=0
num.query.type.TYPE0=21838
num.query.type.A=4576639648
num.query.type.NS=195714
num.query.type.MF=1
num.query.type.CNAME=223477
num.query.type.SOA=252841
num.query.type.MR=2
num.query.type.NULL=238628
num.query.type.WKS=230227
num.query.type.PTR=8446520
num.query.type.HINFO=231428
num.query.type.MX=34204
num.query.type.TXT=510353
num.query.type.AAAA=151992709
num.query.type.NXT=3
num.query.type.SRV=1883446
num.query.type.NAPTR=1578821
num.query.type.DS=215
num.query.type.DNSKEY=252
num.query.type.TYPE65=140375490
num.query.type.TYPE96=1
num.query.type.ANY=82558
num.query.type.other=17173
num.query.class.CLASS0=2
num.query.class.IN=4882932525
num.query.class.CH=1073
num.query.class.HS=3
num.query.class.CLASS5=1
num.query.class.other=21945
num.query.opcode.QUERY=4882955549
num.query.tcp=353856
num.query.tcpout=8035409
num.query.tls=0
num.query.tls.resume=0
num.query.ipv6=0
num.query.flags.QR=0
num.query.flags.AA=4780
num.query.flags.TC=0
num.query.flags.RD=4881598247
num.query.flags.RA=1963578
num.query.flags.Z=125956
num.query.flags.AD=406164
num.query.flags.CD=348932
num.query.edns.present=1544145
num.query.edns.DO=559536
num.answer.rcode.NOERROR=4541650937
num.answer.rcode.FORMERR=74634
num.answer.rcode.SERVFAIL=27118108
num.answer.rcode.NXDOMAIN=258691024
num.answer.rcode.NOTIMPL=82358
num.answer.rcode.REFUSED=1126718
num.answer.rcode.nodata=143652060
num.query.ratelimited=0
num.answer.secure=50709972
num.answer.bogus=118372
num.rrset.bogus=435
num.query.aggressive.NOERROR=14204
num.query.aggressive.NXDOMAIN=3
unwanted.queries=0
unwanted.replies=189737
msg.cache.count=1800872
rrset.cache.count=1411946
infra.cache.count=986445
key.cache.count=378804
num.query.authzone.up=0
num.query.authzone.down=0
num.query.subnet=0
num.query.subnet_cache=0

**Comment by svartalf** [comment]
Hi, @mahdiadnan and thanks for bug report!

I reworked support of "unnamed" classes/rtypes/rcodes/etc in f1cda8bceb3634d92d98561595dfef5f8db6b103 and it was merged into the `master` branch already; can you check it?

**Comment by mahdiadnan** [comment]
Thank you @svartalf now I'm getting another error and I don't know if this due to the latest commit or it was already there;
"Unable to observe unbound statistics: Unable to parse 'ANY' value"


thread0.num.queries=985095805
thread0.num.queries_ip_ratelimited=0
thread0.num.cachehits=947301304
thread0.num.cachemiss=37794501
thread0.num.prefetch=7233960
thread0.num.zero_ttl=0
thread0.num.recursivereplies=37794401
thread0.requestlist.avg=106.25
thread0.requestlist.max=1808
thread0.requestlist.overwritten=0
thread0.requestlist.exceeded=0
thread0.requestlist.current.all=173
thread0.requestlist.current.user=100
thread0.recursion.time.avg=0.314281
thread0.recursion.time.median=0.105205
thread0.tcpusage=3
thread1.num.queries=987502360
thread1.num.queries_ip_ratelimited=0
thread1.num.cachehits=949328494
thread1.num.cachemiss=38173866
thread1.num.prefetch=7232716
thread1.num.zero_ttl=0
thread1.num.recursivereplies=38173800
thread1.requestlist.avg=107.274
thread1.requestlist.max=1919
thread1.requestlist.overwritten=0
thread1.requestlist.exceeded=0
thread1.requestlist.current.all=137
thread1.requestlist.current.user=66
thread1.recursion.time.avg=0.317283
thread1.recursion.time.median=0.105145
thread1.tcpusage=1
thread2.num.queries=984668733
thread2.num.queries_ip_ratelimited=0
thread2.num.cachehits=947410549
thread2.num.cachemiss=37258184
thread2.num.prefetch=7228171
thread2.num.zero_ttl=0
thread2.num.recursivereplies=37258132
thread2.requestlist.avg=105.991
thread2.requestlist.max=2012
thread2.requestlist.overwritten=0
thread2.requestlist.exceeded=0
thread2.requestlist.current.all=118
thread2.requestlist.current.user=52
thread2.recursion.time.avg=0.320259
thread2.recursion.time.median=0.105224
thread2.tcpusage=4
thread3.num.queries=983114953
thread3.num.queries_ip_ratelimited=0
thread3.num.cachehits=945116847
thread3.num.cachemiss=37998106
thread3.num.prefetch=7235172
thread3.num.zero_ttl=0
thread3.num.recursivereplies=37998042
thread3.requestlist.avg=106.677
thread3.requestlist.max=1876
thread3.requestlist.overwritten=0
thread3.requestlist.exceeded=0
thread3.requestlist.current.all=125
thread3.requestlist.current.user=64
thread3.recursion.time.avg=0.316428
thread3.recursion.time.median=0.105095
thread3.tcpusage=1
thread4.num.queries=984897444
thread4.num.queries_ip_ratelimited=0
thread4.num.cachehits=946825207
thread4.num.cachemiss=38072237
thread4.num.prefetch=7235224
thread4.num.zero_ttl=0
thread4.num.recursivereplies=38072160
thread4.requestlist.avg=106.581
thread4.requestlist.max=2091
thread4.requestlist.overwritten=0
thread4.requestlist.exceeded=0
thread4.requestlist.current.all=146
thread4.requestlist.current.user=77
thread4.recursion.time.avg=0.316017
thread4.recursion.time.median=0.105159
thread4.tcpusage=2
thread5.num.queries=984732567
thread5.num.queries_ip_ratelimited=0
thread5.num.cachehits=947434987
thread5.num.cachemiss=37297580
thread5.num.prefetch=7222852
thread5.num.zero_ttl=0
thread5.num.recursivereplies=37297499
thread5.requestlist.avg=105.927
thread5.requestlist.max=1873
thread5.requestlist.overwritten=0
thread5.requestlist.exceeded=0
thread5.requestlist.current.all=146
thread5.requestlist.current.user=81
thread5.recursion.time.avg=0.318048
thread5.recursion.time.median=0.105072
thread5.tcpusage=2
thread6.num.queries=982756704
thread6.num.queries_ip_ratelimited=0
thread6.num.cachehits=944865209
thread6.num.cachemiss=37891495
thread6.num.prefetch=7238696
thread6.num.zero_ttl=0
thread6.num.recursivereplies=37891418
thread6.requestlist.avg=105.834
thread6.requestlist.max=1899
thread6.requestlist.overwritten=0
thread6.requestlist.exceeded=0
thread6.requestlist.current.all=144
thread6.requestlist.current.user=77
thread6.recursion.time.avg=0.312762
thread6.recursion.time.median=0.105101
thread6.tcpusage=3
thread7.num.queries=981939342
thread7.num.queries_ip_ratelimited=0
thread7.num.cachehits=944479310
thread7.num.cachemiss=37460032
thread7.num.prefetch=7219904
thread7.num.zero_ttl=0
thread7.num.recursivereplies=37459965
thread7.requestlist.avg=106.267
thread7.requestlist.max=1940
thread7.requestlist.overwritten=0
thread7.requestlist.exceeded=0
thread7.requestlist.current.all=127
thread7.requestlist.current.user=67
thread7.recursion.time.avg=0.317955
thread7.recursion.time.median=0.105069
thread7.tcpusage=3
total.num.queries=7874707908
total.num.queries_ip_ratelimited=0
total.num.cachehits=7572761907
total.num.cachemiss=301946001
total.num.prefetch=57846695
total.num.zero_ttl=0
total.num.recursivereplies=301945417
total.requestlist.avg=106.353
total.requestlist.max=2091
total.requestlist.overwritten=0
total.requestlist.exceeded=0
total.requestlist.current.all=1116
total.requestlist.current.user=584
total.recursion.time.avg=0.316618
total.recursion.time.median=0.105134
total.tcpusage=19
time.now=1609696007.177272
time.up=285249.831142
time.elapsed=285249.831142
mem.cache.rrset=570424521
mem.cache.message=570425330
mem.mod.iterator=16588
mem.mod.validator=197646123
mem.mod.respip=0
mem.mod.subnet=140552
mem.mod.ipsecmod=0
mem.streamwait=0
histogram.000000.000000.to.000000.000001=22210565
histogram.000000.000001.to.000000.000002=0
histogram.000000.000002.to.000000.000004=0
histogram.000000.000004.to.000000.000008=0
histogram.000000.000008.to.000000.000016=0
histogram.000000.000016.to.000000.000032=1
histogram.000000.000032.to.000000.000064=150
histogram.000000.000064.to.000000.000128=631
histogram.000000.000128.to.000000.000256=1075
histogram.000000.000256.to.000000.000512=2179
histogram.000000.000512.to.000000.001024=4067
histogram.000000.001024.to.000000.002048=8246
histogram.000000.002048.to.000000.004096=17842
histogram.000000.004096.to.000000.008192=3930861
histogram.000000.008192.to.000000.016384=3813428
histogram.000000.016384.to.000000.032768=678543
histogram.000000.032768.to.000000.065536=314791
histogram.000000.065536.to.000000.131072=198590687
histogram.000000.131072.to.000000.262144=35596536
histogram.000000.262144.to.000000.524288=26417261
histogram.000000.524288.to.000001.000000=4498704
histogram.000001.000000.to.000002.000000=2876079
histogram.000002.000000.to.000004.000000=2198999
histogram.000004.000000.to.000008.000000=252963
histogram.000008.000000.to.000016.000000=183676
histogram.000016.000000.to.000032.000000=194689
histogram.000032.000000.to.000064.000000=48694
histogram.000064.000000.to.000128.000000=37372
histogram.000128.000000.to.000256.000000=17926
histogram.000256.000000.to.000512.000000=21135
histogram.000512.000000.to.001024.000000=24138
histogram.001024.000000.to.002048.000000=4120
histogram.002048.000000.to.004096.000000=58
histogram.004096.000000.to.008192.000000=1
histogram.008192.000000.to.016384.000000=0
histogram.016384.000000.to.032768.000000=0
histogram.032768.000000.to.065536.000000=0
histogram.065536.000000.to.131072.000000=0
histogram.131072.000000.to.262144.000000=0
histogram.262144.000000.to.524288.000000=0
num.query.type.TYPE0=34065
num.query.type.A=7384818700
num.query.type.NS=317035
num.query.type.MF=1
num.query.type.CNAME=359771
num.query.type.SOA=408307
num.query.type.MR=2
num.query.type.NULL=369858
num.query.type.WKS=369832
num.query.type.PTR=13133967
num.query.type.HINFO=371946
num.query.type.MX=48396
num.query.type.TXT=874147
num.query.type.AAAA=242139817
num.query.type.NXT=3
num.query.type.SRV=3184572
num.query.type.NAPTR=2545702
num.query.type.DS=373
num.query.type.RRSIG=3
num.query.type.DNSKEY=521
num.query.type.TYPE65=225368934
num.query.type.TYPE96=1
num.query.type.AXFR=10
num.query.type.ANY=106797
num.query.type.other=27452
num.query.class.CLASS0=4
num.query.class.IN=7874443947
num.query.class.CH=1765
num.query.class.HS=3
num.query.class.CLASS5=1
num.query.class.ANY=296
num.query.class.other=34186
num.query.opcode.QUERY=7874480202
num.query.tcp=520954
num.query.tcpout=14555085
num.query.tls=0
num.query.tls.resume=0
num.query.ipv6=0
num.query.flags.QR=0
num.query.flags.AA=7462
num.query.flags.TC=0
num.query.flags.RD=7872239640
num.query.flags.RA=3074458
num.query.flags.Z=202926
num.query.flags.AD=658588
num.query.flags.CD=576747
num.query.edns.present=2486179
num.query.edns.DO=921038
num.answer.rcode.NOERROR=7311910542
num.answer.rcode.FORMERR=117057
num.answer.rcode.SERVFAIL=42825876
num.answer.rcode.NXDOMAIN=426415089
num.answer.rcode.NOTIMPL=106093
num.answer.rcode.REFUSED=1817253
num.answer.rcode.nodata=230480700
num.query.ratelimited=0
num.answer.secure=80154641
num.answer.bogus=166941
num.rrset.bogus=734
num.query.aggressive.NOERROR=22451
num.query.aggressive.NXDOMAIN=3
unwanted.queries=0
unwanted.replies=332174
msg.cache.count=1775349
rrset.cache.count=1491814
infra.cache.count=1286271
key.cache.count=526333
num.query.authzone.up=0
num.query.authzone.down=0
num.query.subnet=0
num.query.subnet_cache=0

**Comment by svartalf** [comment]
Ah, okay. I replaced internal types with `domain` library (which is, same to `unbound` itself, created by NlNet Labs) and its string representation for query class `ANY` is `"*"`, not `"ANY"`, which causes parsing to fail.

Just pushed 575208d7c1da318009758fd6e19c95286abc24c1, which should fix this issue. Thank you for testing!

**Comment by mahdiadnan** [comment]
I've tested the latest master and it works now, thank you @svartalf
