### ISSUE TITLE
Unable to observe unbound statistics: Unable to parse 'NSAP-PTR' value

### ISSUE THREAD

**Issue by manish-yadav** [svartalf/unbound-telemetry#39]
Hi,

I'm getting the following error:
Unable to observe unbound statistics: Unable to parse 'NSAP-PTR' value

root@ERS-203:~# unbound-control  stats
thread0.num.queries=12627360
thread0.num.queries_ip_ratelimited=0
thread0.num.cachehits=12292681
thread0.num.cachemiss=334679
thread0.num.prefetch=363908
thread0.num.zero_ttl=286002
thread0.num.recursivereplies=334671
thread0.requestlist.avg=23.5715
thread0.requestlist.max=905
thread0.requestlist.overwritten=0
thread0.requestlist.exceeded=0
thread0.requestlist.current.all=19
thread0.requestlist.current.user=8
thread0.recursion.time.avg=0.471094
thread0.recursion.time.median=0.0615196
thread0.tcpusage=1
thread1.num.queries=12483349
thread1.num.queries_ip_ratelimited=0
thread1.num.cachehits=12147541
thread1.num.cachemiss=335808
thread1.num.prefetch=379956
thread1.num.zero_ttl=301021
thread1.num.recursivereplies=335799
thread1.requestlist.avg=24.4879
thread1.requestlist.max=855
thread1.requestlist.overwritten=0
thread1.requestlist.exceeded=0
thread1.requestlist.current.all=14
thread1.requestlist.current.user=6
thread1.recursion.time.avg=0.580630
thread1.recursion.time.median=0.0662706
thread1.tcpusage=0
thread2.num.queries=12675382
thread2.num.queries_ip_ratelimited=0
thread2.num.cachehits=12304968
thread2.num.cachemiss=370414
thread2.num.prefetch=392516
thread2.num.zero_ttl=299106
thread2.num.recursivereplies=370411
thread2.requestlist.avg=28.9079
thread2.requestlist.max=823
thread2.requestlist.overwritten=0
thread2.requestlist.exceeded=0
thread2.requestlist.current.all=19
thread2.requestlist.current.user=1
thread2.recursion.time.avg=0.603078
thread2.recursion.time.median=0.0790135
thread2.tcpusage=0
thread3.num.queries=13058721
thread3.num.queries_ip_ratelimited=0
thread3.num.cachehits=12636539
thread3.num.cachemiss=422182
thread3.num.prefetch=484305
thread3.num.zero_ttl=363643
thread3.num.recursivereplies=422150
thread3.requestlist.avg=54.9533
thread3.requestlist.max=874
thread3.requestlist.overwritten=0
thread3.requestlist.exceeded=0
thread3.requestlist.current.all=56
thread3.requestlist.current.user=32
thread3.recursion.time.avg=0.556060
thread3.recursion.time.median=0.0992251
thread3.tcpusage=4
thread4.num.queries=13459709
thread4.num.queries_ip_ratelimited=0
thread4.num.cachehits=12925374
thread4.num.cachemiss=534335
thread4.num.prefetch=506220
thread4.num.zero_ttl=376395
thread4.num.recursivereplies=534324
thread4.requestlist.avg=30.1408
thread4.requestlist.max=808
thread4.requestlist.overwritten=0
thread4.requestlist.exceeded=0
thread4.requestlist.current.all=16
thread4.requestlist.current.user=9
thread4.recursion.time.avg=0.449964
thread4.recursion.time.median=0.0764512
thread4.tcpusage=1
thread5.num.queries=12728479
thread5.num.queries_ip_ratelimited=0
thread5.num.cachehits=12386985
thread5.num.cachemiss=341494
thread5.num.prefetch=413588
thread5.num.zero_ttl=332805
thread5.num.recursivereplies=341489
thread5.requestlist.avg=24.5389
thread5.requestlist.max=826
thread5.requestlist.overwritten=0
thread5.requestlist.exceeded=0
thread5.requestlist.current.all=19
thread5.requestlist.current.user=3
thread5.recursion.time.avg=0.608134
thread5.recursion.time.median=0.0652771
thread5.tcpusage=1
thread6.num.queries=12579941
thread6.num.queries_ip_ratelimited=0
thread6.num.cachehits=12238847
thread6.num.cachemiss=341094
thread6.num.prefetch=377053
thread6.num.zero_ttl=294330
thread6.num.recursivereplies=341093
thread6.requestlist.avg=23.1885
thread6.requestlist.max=751
thread6.requestlist.overwritten=0
thread6.requestlist.exceeded=0
thread6.requestlist.current.all=13
thread6.requestlist.current.user=0
thread6.recursion.time.avg=0.515187
thread6.recursion.time.median=0.0675836
thread6.tcpusage=0
total.num.queries=89612941
total.num.queries_ip_ratelimited=0
total.num.cachehits=86932935
total.num.cachemiss=2680006
total.num.prefetch=2917546
total.num.zero_ttl=2253302
total.num.recursivereplies=2679937
total.requestlist.avg=30.8006
total.requestlist.max=905
total.requestlist.overwritten=0
total.requestlist.exceeded=0
total.requestlist.current.all=156
total.requestlist.current.user=59
total.recursion.time.avg=0.535307
total.recursion.time.median=0.0736201
total.tcpusage=7
time.now=1609950562.475494
time.up=21771.934211
time.elapsed=21771.934211
mem.cache.rrset=453388560
mem.cache.message=548318318
mem.mod.iterator=16588
mem.mod.validator=8912304
mem.mod.respip=0
mem.mod.subnet=140552
mem.streamwait=0
histogram.000000.000000.to.000000.000001=691633
histogram.000000.000001.to.000000.000002=0
histogram.000000.000002.to.000000.000004=0
histogram.000000.000004.to.000000.000008=0
histogram.000000.000008.to.000000.000016=0
histogram.000000.000016.to.000000.000032=9
histogram.000000.000032.to.000000.000064=15
histogram.000000.000064.to.000000.000128=16
histogram.000000.000128.to.000000.000256=50
histogram.000000.000256.to.000000.000512=88
histogram.000000.000512.to.000000.001024=174
histogram.000000.001024.to.000000.002048=412
histogram.000000.002048.to.000000.004096=829
histogram.000000.004096.to.000000.008192=2215
histogram.000000.008192.to.000000.016384=62065
histogram.000000.016384.to.000000.032768=105034
histogram.000000.032768.to.000000.065536=438177
histogram.000000.065536.to.000000.131072=341679
histogram.000000.131072.to.000000.262144=613722
histogram.000000.262144.to.000000.524288=272680
histogram.000000.524288.to.000001.000000=87752
histogram.000001.000000.to.000002.000000=27591
histogram.000002.000000.to.000004.000000=16068
histogram.000004.000000.to.000008.000000=7067
histogram.000008.000000.to.000016.000000=4225
histogram.000016.000000.to.000032.000000=4091
histogram.000032.000000.to.000064.000000=1620
histogram.000064.000000.to.000128.000000=889
histogram.000128.000000.to.000256.000000=640
histogram.000256.000000.to.000512.000000=877
histogram.000512.000000.to.001024.000000=287
histogram.001024.000000.to.002048.000000=26
histogram.002048.000000.to.004096.000000=5
histogram.004096.000000.to.008192.000000=1
histogram.008192.000000.to.016384.000000=0
histogram.016384.000000.to.032768.000000=0
histogram.032768.000000.to.065536.000000=0
histogram.065536.000000.to.131072.000000=0
histogram.131072.000000.to.262144.000000=0
histogram.262144.000000.to.524288.000000=0
num.query.type.TYPE0=2869
num.query.type.A=73456559
num.query.type.NS=19355
num.query.type.MD=1
num.query.type.CNAME=3518
num.query.type.SOA=102213
num.query.type.NULL=8
num.query.type.WKS=2831
num.query.type.PTR=796892
num.query.type.HINFO=2869
num.query.type.MX=5877
num.query.type.TXT=422067
num.query.type.NSAP-PTR=1
num.query.type.AAAA=9258386
num.query.type.SRV=1244403
num.query.type.NAPTR=67774
num.query.type.DS=1922
num.query.type.RRSIG=2242
num.query.type.DNSKEY=578
num.query.type.TYPE65=4139593
num.query.type.TYPE128=2
num.query.type.TYPE136=2
num.query.type.ANY=81211
num.query.type.other=81
num.query.class.CLASS0=7
num.query.class.IN=89604457
num.query.class.CLASS2=1
num.query.class.CH=131
num.query.class.CLASS6=1
num.query.class.CLASS54=1
num.query.class.ANY=120
num.query.class.other=6532
num.query.opcode.QUERY=89611250
num.query.tcp=101689
num.query.tcpout=161659
num.query.tls=0
num.query.tls.resume=0
num.query.ipv6=0
num.query.flags.QR=0
num.query.flags.AA=23271
num.query.flags.TC=0
num.query.flags.RD=89600199
num.query.flags.RA=15645
num.query.flags.Z=1458
num.query.flags.AD=10127
num.query.flags.CD=6886
num.query.edns.present=589847
num.query.edns.DO=16376
num.answer.rcode.NOERROR=76112012
num.answer.rcode.FORMERR=887
num.answer.rcode.SERVFAIL=314176
num.answer.rcode.NXDOMAIN=10929563
num.answer.rcode.NOTIMPL=0
num.answer.rcode.REFUSED=2255430
num.answer.rcode.nodata=5911499
num.query.ratelimited=0
num.answer.secure=2697235
num.answer.bogus=1553
num.rrset.bogus=564
num.query.aggressive.NOERROR=13172
num.query.aggressive.NXDOMAIN=21
unwanted.queries=0
unwanted.replies=1635
msg.cache.count=1724314
rrset.cache.count=1235845
infra.cache.count=9941
key.cache.count=18014
num.query.authzone.up=0
num.query.authzone.down=0
num.query.subnet=0

**Comment by svartalf** [comment]
Fixed in 9684d699616b6331b96e35903a148fb52dd7f2d8, please check it.
