### ISSUE TITLE
Unbound statistics

### ISSUE THREAD

**Issue by cardosocristian** [svartalf/unbound-telemetry#49]
Hi
I'm using unbound in version 1.13.1, the remote control is active on the system's standard port, when I try to use telemetry via tcp, it is only shown in the metrics tab that unbound is up and nothing else, even with the option " extendend statistics: yes ".

If I try to use via shm or uds, I get the following error:" # Unable to observe unbound statistics: No such file or directory (os error 2) "

Did that happen in your use?

**Comment by svartalf** [comment]
Hey, @cardosocristian!

Is there anything in the process stdout or at the open metrics export URL (available at http://0.0.0.0:9167/metrics by default)?
If you have `unbound_up` metric available and it is set to `1`, I would expect at least TCP connection to work properly, so please provide more information.

**Comment by cardosocristian** [comment]
When I run the process via tcp, there are no command outputs, just normal execution, as follows:

# ./unbound-telemetry tcp
INFO [unbound_telemetry :: server] Listening on 0.0.0.0:9167

The remote control port is active, as follows:
# sockstat -l | grep 8953
unbound unbound 25750 11 tcp4 127.0.0.1:8953 *: *

In the config I also have the options:
    statistics-interval: 0
    extended-statistics: yes
    statistics-cumulative: yes

Below is the output of /metrics being displayed in the browser

# TYPE unbound_num_threads gauge
# HELP unbound_num_threads The number of threads to create to serve clients
unbound_num_threads 0
# TYPE unbound_time_up_seconds_total counter
# HELP unbound_time_up_seconds_total Uptime since server boot in seconds
unbound_time_up_seconds_total 0.0
# TYPE unbound_time_now_seconds counter
# HELP unbound_time_now_seconds Current time in seconds since UNIX epoch
unbound_time_now_seconds 0.0
# TYPE unbound_time_elapsed_seconds counter
# HELP unbound_time_elapsed_seconds Time since last statistics printout in seconds
unbound_time_elapsed_seconds 0.0
# TYPE unbound_memory_caches_bytes gauge
# HELP unbound_memory_caches_bytes Memory in bytes in use by caches
unbound_memory_caches_bytes{cache="rrset"} 0
unbound_memory_caches_bytes{cache="message"} 0
unbound_memory_caches_bytes{cache="dnscrypt_shared_secret"} 0
unbound_memory_caches_bytes{cache="dnscrypt_nonce"} 0
# TYPE unbound_memory_modules_bytes gauge
# HELP unbound_memory_modules_bytes Memory in bytes in use by modules
unbound_memory_modules_bytes{module="iterator"} 0
unbound_memory_modules_bytes{module="validator"} 0
unbound_memory_modules_bytes{module="respip"} 0
unbound_memory_modules_bytes{module="subnet"} 0
# TYPE unbound_memory_http_bytes gauge
# HELP unbound_memory_http_bytes Memory in bytes in use by HTTP/2 queries
unbound_memory_http_bytes{http="query_buffer"} 0
unbound_memory_http_bytes{http="response_buffer"} 0
# TYPE unbound_memory_stream_wait_count gauge
# HELP unbound_memory_stream_wait_count The number of bytes in the stream wait buffers
unbound_memory_stream_wait_count 0
# TYPE unbound_query_tcp_total counter
# HELP unbound_query_tcp_total Total number of queries that were made using TCP towards the server
unbound_query_tcp_total 0
# TYPE unbound_query_tcp_out_total counter
# HELP unbound_query_tcp_out_total Total number of queries that were made using TCP outwards the server
unbound_query_tcp_out_total 0
# TYPE unbound_query_tls_total counter
# HELP unbound_query_tls_total Total number of queries that were made using TLS towards the server
unbound_query_tls_total 0
# TYPE unbound_query_tls_resume_total counter
# HELP unbound_query_tls_resume_total Total number of queries that were made using TLS resumption
unbound_query_tls_resume_total 0
# TYPE unbound_query_ipv6_total counter
# HELP unbound_query_ipv6_total Total number of queries that were made using IPv6 toward the server
unbound_query_ipv6_total 0
# TYPE unbound_query_https_total counter
# HELP unbound_query_https_total Total number of queries that were made using HTTPS
unbound_query_https_total 0
# TYPE unbound_query_edns_DO_total counter
# HELP unbound_query_edns_DO_total Total number of queries that had an EDNS OPT record with the DO (DNSSEC OK) bit set present
unbound_query_edns_DO_total 0
# TYPE unbound_query_edns_present_total counter
# HELP unbound_query_edns_present_total Total number of queries that had an EDNS OPT record present
unbound_query_edns_present_total 0
# TYPE unbound_query_ratelimited_total counter
# HELP unbound_query_ratelimited_total Total number of queries that had been rate limited
unbound_query_ratelimited_total 0
# TYPE unbound_answers_secure_total counter
# HELP unbound_answers_secure_total Total amount of answers that were secure (AD)
unbound_answers_secure_total 0
# TYPE unbound_answers_bogus counter
# HELP unbound_answers_bogus Total amount of answers that were bogus (withheld as SERVFAIL)
unbound_answers_bogus 0
# TYPE unbound_answers_bogus_total counter
# HELP unbound_answers_bogus_total Total amount of answers that were bogus (withheld as SERVFAIL)
unbound_answers_bogus_total 0
# TYPE unbound_rrset_bogus_total counter
# HELP unbound_rrset_bogus_total Total number of rrsets marked bogus by the validator
unbound_rrset_bogus_total 0
# TYPE unbound_msg_cache_count gauge
# HELP unbound_msg_cache_count The number of messages cached
unbound_msg_cache_count 0
# TYPE unbound_rrset_cache_count gauge
# HELP unbound_rrset_cache_count The number of rrset cached
unbound_rrset_cache_count 0
# TYPE unbound_cache_count_total gauge
# HELP unbound_cache_count_total The number of cached entries
unbound_cache_count_total{type="message"} 0
unbound_cache_count_total{type="rrset"} 0
unbound_cache_count_total{type="key"} 0
unbound_cache_count_total{type="infra"} 0
unbound_cache_count_total{type="dnscrypt_nonce"} 0
unbound_cache_count_total{type="dnscrypt_shared_secret"} 0
# TYPE unbound_unwanted_queries_total counter
# HELP unbound_unwanted_queries_total Total number of queries that were refused or dropped because they failed the access control settings.
unbound_unwanted_queries_total 0
# TYPE unbound_unwanted_replies_total counter
# HELP unbound_unwanted_replies_total Total number of replies that were unwanted or unsolicited
unbound_unwanted_replies_total 0
# TYPE unbound_query_types_total counter
# HELP unbound_query_types_total Total number of queries with a given query type
unbound_query_types_total{type="other"} 0
# TYPE unbound_query_classes_total counter
# HELP unbound_query_classes_total Total number of queries with a given query class
unbound_query_classes_total{class="other"} 0
# TYPE unbound_query_flags_total counter
# HELP unbound_query_flags_total Total number of queries that had a given flag set in the header
unbound_query_flags_total{flag="QR"} 0
unbound_query_flags_total{flag="AA"} 0
unbound_query_flags_total{flag="TC"} 0
unbound_query_flags_total{flag="RD"} 0
unbound_query_flags_total{flag="RA"} 0
unbound_query_flags_total{flag="Z"} 0
unbound_query_flags_total{flag="AD"} 0
unbound_query_flags_total{flag="CD"} 0
# TYPE unbound_response_time_seconds histogram
# HELP unbound_response_time_seconds Query response time in seconds
unbound_response_time_seconds_sum 0.0
unbound_response_time_seconds_count 0
unbound_response_time_seconds_bucket{le="+Inf"} 0
# TYPE unbound_up counter
# HELP unbound_up This Unbound instance is up and running
unbound_up 1
# TYPE unbound_scrape_duration_seconds gauge
# HELP unbound_scrape_duration_seconds Time spent on metrics scraping
unbound_scrape_duration_seconds 0.000564673


I'm running unbound on a server with FreeBSD 12.2-RELEASE

The version of Rust I'm using is 1.48
# pkg info rust
rust-1.48.0
Name: rust
Version: 1.48.0

**Comment by svartalf** [comment]
I hope you do not mind, but I edited your reply just a bit and added Markdown for code blocks, because it was hard to read it.

Considering that you have all needed metrics, I can assume that exporter is being able to connect to the `unbound` instance just fine (you can also double-check it by opening `/healthcheck` URL), but there are no metrics provided by `unbound` itself.

Can you also try to run [`unbound-control`](https://nlnetlabs.nl/documentation/unbound/unbound-control/) to check if everything is correct on the other side?
In a simple case, it should work like this if executed on the same machine:
```
$ unbound-control stats_noreset
```

**Comment by cardosocristian** [comment]
```
# unbound-control stats_noreset
thread0.num.queries=113880440
thread0.num.queries_ip_ratelimited=0
thread0.num.cachehits=97198592
thread0.num.cachemiss=16681848
thread0.num.prefetch=0
thread0.num.expired=0
thread0.num.recursivereplies=16313159
thread0.requestlist.avg=30.7514
thread0.requestlist.max=244
thread0.requestlist.overwritten=49779
thread0.requestlist.exceeded=318044
thread0.requestlist.current.all=36
thread0.requestlist.current.user=33
thread0.recursion.time.avg=0.207493
thread0.recursion.time.median=0.184365
thread0.tcpusage=0
thread1.num.queries=187316157
thread1.num.queries_ip_ratelimited=0
thread1.num.cachehits=161637261
thread1.num.cachemiss=25678896
thread1.num.prefetch=0
thread1.num.expired=0
thread1.num.recursivereplies=25120995
thread1.requestlist.avg=36.7392
thread1.requestlist.max=245
thread1.requestlist.overwritten=73167
thread1.requestlist.exceeded=483213
thread1.requestlist.current.all=50
thread1.requestlist.current.user=43
thread1.recursion.time.avg=0.207531
thread1.recursion.time.median=0.183197
thread1.tcpusage=0
thread2.num.queries=54315501
thread2.num.queries_ip_ratelimited=0
thread2.num.cachehits=45626061
thread2.num.cachemiss=8689440
thread2.num.prefetch=0
thread2.num.expired=0
thread2.num.recursivereplies=8507181
thread2.requestlist.avg=22.4091
thread2.requestlist.max=243
thread2.requestlist.overwritten=30371
thread2.requestlist.exceeded=151446
thread2.requestlist.current.all=21
thread2.requestlist.current.user=18
thread2.recursion.time.avg=0.209408
thread2.recursion.time.median=0.185711
thread2.tcpusage=0
thread3.num.queries=42476587
thread3.num.queries_ip_ratelimited=0
thread3.num.cachehits=35424328
thread3.num.cachemiss=7052259
thread3.num.prefetch=0
thread3.num.expired=0
thread3.num.recursivereplies=6914805
thread3.requestlist.avg=21.02
thread3.requestlist.max=220
thread3.requestlist.overwritten=23895
thread3.requestlist.exceeded=113250
thread3.requestlist.current.all=20
thread3.requestlist.current.user=17
thread3.recursion.time.avg=0.207707
thread3.recursion.time.median=0.18569
thread3.tcpusage=0
total.num.queries=397988685
total.num.queries_ip_ratelimited=0
total.num.cachehits=339886242
total.num.cachemiss=58102443
total.num.prefetch=0
total.num.expired=0
total.num.recursivereplies=56856140
total.requestlist.avg=30.969
total.requestlist.max=245
total.requestlist.overwritten=177212
total.requestlist.exceeded=1065953
total.requestlist.current.all=127
total.requestlist.current.user=111
total.recursion.time.avg=0.207822
total.recursion.time.median=0.184741
total.tcpusage=0
time.now=1616074334.993275
time.up=259198.728766
time.elapsed=134.959101
mem.cache.rrset=1062681993
mem.cache.message=1207959306
mem.mod.iterator=16556
mem.mod.validator=8912423
mem.mod.respip=0
mem.mod.subnet=0
mem.mod.ipsecmod=0
mem.streamwait=0
mem.http.query_buffer=0
mem.http.response_buffer=0
histogram.000000.000000.to.000000.000001=61443
histogram.000000.000001.to.000000.000002=0
histogram.000000.000002.to.000000.000004=0
histogram.000000.000004.to.000000.000008=30
histogram.000000.000008.to.000000.000016=147
histogram.000000.000016.to.000000.000032=134
histogram.000000.000032.to.000000.000064=159
histogram.000000.000064.to.000000.000128=443
histogram.000000.000128.to.000000.000256=976
histogram.000000.000256.to.000000.000512=1868
histogram.000000.000512.to.000000.001024=18524
histogram.000000.001024.to.000000.002048=840967
histogram.000000.002048.to.000000.004096=2047896
histogram.000000.004096.to.000000.008192=2695649
histogram.000000.008192.to.000000.016384=1651444
histogram.000000.016384.to.000000.032768=333486
histogram.000000.032768.to.000000.065536=227975
histogram.000000.065536.to.000000.131072=3707471
histogram.000000.131072.to.000000.262144=41532003
histogram.000000.262144.to.000000.524288=3035441
histogram.000000.524288.to.000001.000000=450250
histogram.000001.000000.to.000002.000000=138474
histogram.000002.000000.to.000004.000000=84547
histogram.000004.000000.to.000008.000000=11648
histogram.000008.000000.to.000016.000000=2848
histogram.000016.000000.to.000032.000000=4627
histogram.000032.000000.to.000064.000000=2161
histogram.000064.000000.to.000128.000000=2942
histogram.000128.000000.to.000256.000000=1530
histogram.000256.000000.to.000512.000000=992
histogram.000512.000000.to.001024.000000=63
histogram.001024.000000.to.002048.000000=2
histogram.002048.000000.to.004096.000000=0
histogram.004096.000000.to.008192.000000=0
histogram.008192.000000.to.016384.000000=0
histogram.016384.000000.to.032768.000000=0
histogram.032768.000000.to.065536.000000=0
histogram.065536.000000.to.131072.000000=0
histogram.131072.000000.to.262144.000000=0
histogram.262144.000000.to.524288.000000=0
num.query.type.A=282248368
num.query.type.NULL=5
num.query.type.PTR=362404
num.query.type.MX=4137113
num.query.type.TXT=82549254
num.query.type.AAAA=28690820
num.query.type.SRV=1
num.query.type.DNSKEY=22
num.query.class.IN=397987987
num.query.opcode.QUERY=397987987
num.query.tcp=23
num.query.tcpout=37209
num.query.tls=0
num.query.tls.resume=0
num.query.ipv6=104
num.query.https=0
num.query.flags.QR=0
num.query.flags.AA=0
num.query.flags.TC=0
num.query.flags.RD=397987795
num.query.flags.RA=0
num.query.flags.Z=0
num.query.flags.AD=1
num.query.flags.CD=192
num.query.edns.present=395407575
num.query.edns.DO=7613
num.answer.rcode.NOERROR=152821742
num.answer.rcode.FORMERR=698
num.answer.rcode.SERVFAIL=155680
num.answer.rcode.NXDOMAIN=243800759
num.answer.rcode.NOTIMPL=0
num.answer.rcode.REFUSED=0
num.answer.rcode.nodata=52420698
num.query.ratelimited=0
num.answer.secure=4040464
num.answer.bogus=63587
num.rrset.bogus=254
num.query.aggressive.NOERROR=38983
num.query.aggressive.NXDOMAIN=0
unwanted.queries=0
unwanted.replies=205
msg.cache.count=4470124
rrset.cache.count=3423585
infra.cache.count=982648
key.cache.count=23874
num.query.authzone.up=30395
num.query.authzone.down=0
num.query.subnet=0
num.query.subnet_cache=0
```

**Comment by svartalf** [comment]
> Apparently everything is ok, because I use the command you mentioned to collect metrics via shell script today.

Well, that still means that `unbound-telemetry` is not able to fetch statistics properly, right? :)
Do you think you can run it with the same arguments for TCP connection and ` --log-level trace` argument added, request metrics collection a couple times and paste whatever there will be printed to `stdout`?

**Comment by cardosocristian** [comment]
```
# ./unbound-telemetry tcp --log-level trace
TRACE [mio::poll] registering with poller
TRACE [mio::sys::unix::kqueue] registering; token=Token(0); interests=Readable | Writable | Error | Hup
INFO  [unbound_telemetry::server] Listening on 0.0.0.0:9167
TRACE [mio::poll] registering with poller
TRACE [mio::sys::unix::kqueue] registering; token=Token(1); interests=Readable | Writable | Error | Hup
TRACE [mio::poll] registering with poller
TRACE [mio::sys::unix::kqueue] registering; token=Token(2); interests=Readable | Writable | Error | Hup
TRACE [hyper::proto::h1::conn] Conn::read_head
TRACE [hyper::proto::h1::conn] flushed({role=server}): State { reading: Init, writing: Init, keep_alive: Busy }
TRACE [mio::poll] registering with poller
TRACE [mio::sys::unix::kqueue] registering; token=Token(3); interests=Readable | Writable | Error | Hup
TRACE [hyper::proto::h1::conn] Conn::read_head
DEBUG [hyper::proto::h1::io] read 455 bytes
TRACE [hyper::proto::h1::role] Request.parse([Header; 100], [u8; 455])
TRACE [hyper::proto::h1::role] Request.parse Complete(455)
DEBUG [hyper::proto::h1::io] parsed 7 headers
DEBUG [hyper::proto::h1::conn] incoming body is empty
TRACE [hyper::proto::h1::role] Server::encode status=200, body=Some(Known(166)), req_method=Some(GET)
DEBUG [hyper::proto::h1::io] flushed 243 bytes
TRACE [hyper::proto::h1::conn] flushed({role=server}): State { reading: Init, writing: Init, keep_alive: Idle }
TRACE [hyper::proto::h1::conn] Conn::read_head
TRACE [hyper::proto::h1::conn] flushed({role=server}): State { reading: Init, writing: Init, keep_alive: Busy }
TRACE [hyper::proto::h1::conn] Conn::read_head
TRACE [hyper::proto::h1::conn] flushed({role=server}): State { reading: Init, writing: Init, keep_alive: Idle }
TRACE [hyper::proto::h1::conn] Conn::read_head
DEBUG [hyper::proto::h1::io] read 400 bytes
TRACE [hyper::proto::h1::role] Request.parse([Header; 100], [u8; 400])
TRACE [hyper::proto::h1::role] Request.parse Complete(400)
DEBUG [hyper::proto::h1::io] parsed 7 headers
DEBUG [hyper::proto::h1::conn] incoming body is empty
TRACE [hyper::proto::h1::role] Server::encode status=404, body=None, req_method=Some(GET)
DEBUG [hyper::proto::h1::io] flushed 82 bytes
TRACE [hyper::proto::h1::conn] flushed({role=server}): State { reading: Init, writing: Init, keep_alive: Idle }
TRACE [hyper::proto::h1::conn] Conn::read_head
TRACE [hyper::proto::h1::conn] flushed({role=server}): State { reading: Init, writing: Init, keep_alive: Idle }
TRACE [hyper::proto::h1::conn] Conn::read_head
DEBUG [hyper::proto::h1::io] read 497 bytes
TRACE [hyper::proto::h1::role] Request.parse([Header; 100], [u8; 497])
TRACE [hyper::proto::h1::role] Request.parse Complete(497)
DEBUG [hyper::proto::h1::io] parsed 8 headers
DEBUG [hyper::proto::h1::conn] incoming body is empty
TRACE [mio::poll] registering with poller
TRACE [mio::sys::unix::kqueue] registering; token=Token(4); interests=Readable | Writable | Error | Hup
TRACE [hyper::proto::h1::conn] flushed({role=server}): State { reading: KeepAlive, writing: Init, keep_alive: Busy }
TRACE [hyper::proto::h1::conn] flushed({role=server}): State { reading: KeepAlive, writing: Init, keep_alive: Busy }
TRACE [hyper::proto::h1::conn] flushed({role=server}): State { reading: KeepAlive, writing: Init, keep_alive: Busy }
TRACE [hyper::proto::h1::conn] flushed({role=server}): State { reading: KeepAlive, writing: Init, keep_alive: Busy }
TRACE [mio::poll] deregistering handle with poller
TRACE [hyper::proto::h1::role] Server::encode status=200, body=Some(Known(6091)), req_method=Some(GET)
DEBUG [hyper::proto::h1::io] flushed 6195 bytes
TRACE [hyper::proto::h1::conn] flushed({role=server}): State { reading: Init, writing: Init, keep_alive: Idle }
TRACE [hyper::proto::h1::conn] Conn::read_head
TRACE [hyper::proto::h1::conn] flushed({role=server}): State { reading: Init, writing: Init, keep_alive: Idle }

TRACE [hyper::proto::h1::conn] Conn::read_head
DEBUG [hyper::proto::h1::io] read 0 bytes
TRACE [hyper::proto::h1::io] parse eof
TRACE [hyper::proto::h1::conn] State::close_read()
DEBUG [hyper::proto::h1::conn] read eof
TRACE [hyper::proto::h1::conn] State::close_write()
TRACE [hyper::proto::h1::conn] State::close_read()
TRACE [hyper::proto::h1::conn] State::close_write()
TRACE [hyper::proto::h1::conn] flushed({role=server}): State { reading: Closed, writing: Closed, keep_alive: Disabled }
TRACE [hyper::proto::h1::conn] shut down IO complete
TRACE [mio::poll] deregistering handle with poller
TRACE [hyper::proto::h1::conn] Conn::read_head
DEBUG [hyper::proto::h1::io] read 523 bytes
TRACE [hyper::proto::h1::role] Request.parse([Header; 100], [u8; 523])
TRACE [hyper::proto::h1::role] Request.parse Complete(523)
DEBUG [hyper::proto::h1::io] parsed 9 headers
DEBUG [hyper::proto::h1::conn] incoming body is empty
TRACE [mio::poll] registering with poller
TRACE [mio::sys::unix::kqueue] registering; token=Token(34359738371); interests=Readable | Writable | Error | Hup
TRACE [hyper::proto::h1::conn] flushed({role=server}): State { reading: KeepAlive, writing: Init, keep_alive: Busy }
TRACE [hyper::proto::h1::conn] flushed({role=server}): State { reading: KeepAlive, writing: Init, keep_alive: Busy }
TRACE [hyper::proto::h1::conn] flushed({role=server}): State { reading: KeepAlive, writing: Init, keep_alive: Busy }
TRACE [hyper::proto::h1::conn] flushed({role=server}): State { reading: KeepAlive, writing: Init, keep_alive: Busy }
TRACE [mio::poll] registering with poller
TRACE [mio::sys::unix::kqueue] registering; token=Token(34359738372); interests=Readable | Writable | Error | Hup
TRACE [hyper::proto::h1::conn] Conn::read_head
TRACE [hyper::proto::h1::conn] flushed({role=server}): State { reading: Init, writing: Init, keep_alive: Busy }
TRACE [mio::poll] deregistering handle with poller
TRACE [hyper::proto::h1::role] Server::encode status=200, body=Some(Known(6091)), req_method=Some(GET)
DEBUG [hyper::proto::h1::io] flushed 6195 bytes
TRACE [hyper::proto::h1::conn] flushed({role=server}): State { reading: Init, writing: Init, keep_alive: Idle }
TRACE [hyper::proto::h1::conn] Conn::read_head
TRACE [hyper::proto::h1::conn] flushed({role=server}): State { reading: Init, writing: Init, keep_alive: Idle }
```
