### ISSUE TITLE
output to file for prometheus node_exporter textfile collector

### ISSUE THREAD

**Issue by furlongm** [svartalf/unbound-telemetry#69]
It would be good to have an option to output to file periodically, rather than binding to a specific port/address. When using the prometheus node_exporter textfile collector this would be very useful.

**Comment by svartalf** [comment]
I'm wondering here if there any other exporters which support that out of the box?
It is feasible to do that, especially considering that output format is the same, but I'm not quite sure if it worth it; so far it seems like a very rare case which can easily be covered by a simple shell script like this one:

```sh
curl http://127.0.0.1:9167/metrics -o unbound_metrics.tmp.txt && mv unbound_metrics.tmp.txt unbound_metrics.txt
```

with cron or systemd timer enabled and textfile collector pointing to `unbound_metrics.txt` file.
